setwd("C:/Users/denise.aoko/Documents/R manenos")
Active <- read.csv("Active on ART.csv")
is.data.frame(Active)
head(Active)
View(Active)
# descriptive statistics
summary(Active$Age.at.Reporting)
names(Active)
gender_count <- table(Active$Sex)
print(gender_count)
dsd_model <- table(Active$Differentiated.Care.Model)
print(dsd_model)
stability <- table(Active$Establishment)
print(stability)
population_type <- table(Active$Popolation.Type)
print(population_type)
# sub-setting data
children <- subset(Active,Age.at.Reporting < 15 & Sex == "F")
print(children)
write.csv(children, file = "children.csv",row.names = FALSE)
children_male <- subset(Active,Age.at.Reporting < 15 & Sex == "M" & Facilty.Name == "Akala Health Centre")
print(children_male)
write.csv(children_male, file = "children_m.csv",row.names = FALSE)
